Sprint 3
AngryFennec/middle.messenger.praktikum.yandex pull request #6
Opened 2021-07-11 15:50 UTC by AngryFennec

2021-07-12 12:17 UTC, DmitryKhitrin requested changes
Привет!

Спасибо за отличную работу, все очень грамотно организовано!) Но есть пара моментов, которые хотелось бы поправить:

- TS - типизация, мощный инструмент, который позволяет порой найти ошибки еще на стадии написания кода, не запуская его. Но все это будет работать, если писать корректный типы без any и ts-ignore

- обработка асинхронных ошибок
- остальное указал в комментах

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/api/auth-api.ts
> +    return new HTTPTransport().get('/auth/user', { headers: { 'content-type': 'application/json' } });
На самом деле, будет удобней создать один инстанс транспорта на все запросы. Таким образом в дальнейшем можно будет организовывать очереди запросов и не положить бекенд)

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/api/chat-api.ts
> +    return new HTTPTransport().get('/chats', { data: JSON.stringify(data), headers: { 'content-type': 'application/json' } });
` { 'content-type': 'application/json' } ` этот хедер можно унести в HTTPTransport как baseHeader и в случае необходимости переопределять

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/api/user-api.ts
> +  public getUserById(data): Promise<void> {
Лучше добавить в ручку парсеры, который будут валидировать ответ бекенда, и отдавать не Promise<void>, а честные Promise<User>

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/common/block.ts
> +    console.log(oldProps);
Лучше не оставлять в коде отладочное логирование

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/common/http-transport.ts
> +  private base = 'https://ya-praktikum.tech/api/v2';
Лучше не хардкодить url в свойствах класса, максимум можно сделать вот так:

```
export class HTTPTransport {
    private baseUrl: string;

    constructor(baseUrl: string = BASE_URL) {
        this.baseUrl = baseUrl;
    }
}
```

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/common/props-type.ts
> +export type PropsType = {
shorType дл таких типов Record -` Record<string, any>;`

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/common/route.ts
> +  private block: any;
Тут не any, а Block

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/common/route.ts
> +  private blockClass: any;
string

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/common/route.ts
> +  private pathname: any;
string

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/common/route.ts
> +  private props: any;
Тут объект

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/common/router.ts
> +      return;
Получается, если пользователь введет не валдный url мы покажем ему белый экран? Кажется тут стоит отдавать 404

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/common/router.ts
> +      // @ts-ignore
Зачем тут ts-ignore?

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/common/utils.ts
> +  const root = document.querySelector(query);
querySelector может вернуть null, тут нужна проверка на наличие элемента

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/common/web-socket-api.ts
> +    this.socket = new WebSocket(`wss://ya-praktikum.tech/ws/chats/${userId}/${chatId}/${chatToken}`);
Давай вынесем путь до сокета в константу?

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/scripts/setChatClick.ts
> +  chatItems.forEach((item: any) => item.addEventListener('click', (evt) => {
Тут точно any?

2021-07-12 12:17 UTC, DmitryKhitrin commented on src/api/auth-api.ts
> +  public logout(): Promise<void> {
По месту вызова функций помимо проверки кода ответа, хорошо бы еще добавить catch, что бы иметь возможность отловить асинхронные ошибки

2021-07-15 13:43 UTC, AngryFennec commented on src/api/user-api.ts
> +  public getUserById(data): Promise<void> {
не поняла про честные промисы, на всякий случай дописала контроллеры всем запросам

2021-07-16 11:00 UTC, DmitryKhitrin commented on src/controllers/auth-controller.ts
> +    }).catch((err) => console.log(err));
👍

2021-07-16 11:01 UTC, DmitryKhitrin approved these changes
Спасибо за внесенные правки)

Удачи в следующем спринте!)

2021-07-19 14:58 UTC, merged